version: "3.9"
services:
  kubo:
    image: "ipfs/kubo"
    ports:
      - "4001:4001/udp"
      - "4001:4001/tcp"
      - "127.0.0.1:5001:5001"
      - "127.0.0.1:8080:8080"
  ganache:
    ports:
      - "8545:8545"
    image: "trufflesuite/ganache:v7.7.7"
